### ISSUE TITLE
Openneuro bulk processing script ignores missing values

### ISSUE THREAD

**Issue by surchs** [neurobagel/.github#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

In the big open neuro tsv we denote missing values by mapping them to the made up controlled term nb:MissingValue. But then we never use this value when making the data dictionaries.

what’s worse: we load the tsv in replace-na mode so many of these values get turned into pandas nans internally (eg “n/a”)

as a result, some datasets fail the cli because we don’t allow unannotated values.

We need to

- read the values portion off the tsv as string (or just everything as string)
- Listen for the special controlled term as signal to put the value in the MissingValues section rather than the Levels section
- Test this
- Rerun data dictionary creation

### Environment

- OS:
- Python/Node version:

**Comment by alyssadai** [comment]
Closing this as an identical issue has been opened in https://github.com/neurobagel/bulk_annotations/issues/23 for easier tracking in the relevant repo.
